# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa113781e8939fb926106be32786c8bd2f05ff9828040e0703e5796a8a63ffb0a9aa02364a19b43e544fdbdadb0eb47dcfdf8420626fd94ffdeba7e91c03e43f

test:
  secret_key_base: b2408b9414db8cdeba5b60e6fe1504e0f808312d1f268e5c8c621f23e18b1e6d5ad46d557f2e18fc0de7dcb251ee0dad1915b2c5188b18edfeb0de8836f2b991

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
